### ISSUE TITLE
Warning: pattern.indexOf is not a function

### ISSUE THREAD

**Issue by iamchriswick** [ubilabs/grunt-gcloud#7]
I'm getting the following error:

`Running "gcloud:files" (gcloud) task`
`Warning: pattern.indexOf is not a function Use --force to continue.`
`Aborted due to warnings.`

Thoughts?

**Comment by lucasgranberg** [comment]
Old question but I got the same problem. I had to define a target(dist) in my config to get it to work. The readme is wrong.

**old**
```js
gcloud: {
            options: {
                projectId: 'projectid',
                bucket: 'bucket',
                keyFilename: '.gcloud.json'
            },
            files: [{
                src: 'dist/**/*'
            }]
        }
}
```
**new**
```js
gcloud: {
            options: {
                projectId: 'projectid',
                bucket: 'bucket',
                keyFilename: '.gcloud.json'
            },
            dist: {
                files: [{
                    src: 'dist/**/*'
                }]
            }
        }
}
```

**Comment by yfr** [comment]
Closing this as this seem to solve the problem. This repo is not in active development anymore.
